version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: guest
      POSTGRES_USER: guest
      POSTGRES_DB: iot

  broker:
    image: hivemq/hivemq4
    ports:
    - 8080:8080
    - 1883:1883
